name: dialy on build
on:
  schedule:
    - cron: '30 21 * * *'
    # UTC时间，分别对应了北京时间的8点、13点、19点的整点和30分

jobs:
    deployment:
      runs-on: ubuntu-latest
      steps:
      - name: Deploy Stage
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://mktop.ppdai.com/api/mktop/checkInActivityJoinService/getHomePageInfo'
          method: 'POST'
          customHeaders: '{"cookie": "sajssdk_2015_cross_new_user=1; regSourceId=0; referID=0; fromUrl=https%3A%2F%2Fmktmgm.ppdai.com%2F; referDate=2022-10-10%2016%3A32%3A43; currentUrl=https%3A%2F%2Faccount.ppdai.com%2Fh5%2Flogin%3Freturnurl%3Dhttps%253a%252f%252fmktmgm.ppdai.com%252faccount_mgm%252f; uniqueid=64725da3-f5ed-446c-ba92-fdd071a06154; _ppdaiWaterMark=16653907639930; token=748d83375944f8a7e8ab647dfb073553031ee6ca06aa735102022da0468d88ebda1b24cf69dcf1360be6; openid=7171ca619c737a3a4975097681d64e2d; sensorsdata2015jssdkcross=data%3Aenc%3B%0A%2Fqv%02%03v%7Bp%03lvq%2FG%2FD%3ED%3EpnC%3EFpD%40Dn%40nAFDB%3DFDCE%3EqCAr%3Fq%2F9%2Fsv%01%02%03lvq%2FG%2F%3EE%40p%3E%3DCBE%40%3DrBF%3A%3DF%3F%3FrDrEsCnEo%40%3A%40%3F%3EC%3E%40%3FB%3A%3FCCA%3D%3D%3A%3EE%40p%3E%3DCBE%40%3EqAq%2F9%2F%7D%01%7C%7D%02%2FG%0A%2F1yn%03r%02%03l%03%01nssvpl%02%7C%04%01prl%03%08%7Dr%2FG%2F%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%2F9%2F1yn%03r%02%03l%02rn%01pulxr%08%06%7C%01q%2FG%2F%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BCl%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%2F9%2F1yn%03r%02%03l%01rsr%01%01r%01%2FG%2F%2F%0C9%2F1qr%05vprlvq%2FG%2F%3EE%40p%3E%3DCBE%40%3DrBF%3A%3DF%3F%3FrDrEsCnEo%40%3A%40%3F%3EC%3E%40%3FB%3A%3FCCA%3D%3D%3A%3EE%40p%3E%3DCBE%40%3EqAq%2F%0C"}'
          data: '{}'
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
