name: dialy on build
on:
  schedule:
    - cron: '30 21 * * *'
    # UTC时间，分别对应了北京时间的8点、13点、19点的整点和30分

jobs:
    deployment:
      runs-on: ubuntu-latest
      steps:
      - name: Deploy Stage
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://mktop.ppdai.com/api/mktop/checkInActivityJoinService/getHomePageInfo'
          method: 'POST'
          customHeaders: '{"cookie": "sajssdk_2015_cross_new_user=1; regSourceId=0; referID=0; fromUrl=https%3A%2F%2Fmktop.ppdai.com%2F; referDate=2022-7-27%2011%3A3%3A43; currentUrl=https%3A%2F%2Faccount.ppdai.com%2Fh5%2Flogin%3Freturnurl%3Dhttps%253a%252f%252fmktop.ppdai.com%252fmktop%252fplatform_sign; uniqueid=8ec5fdc6-93a7-41a5-be2f-7375b259d655; _ppdaiWaterMark=16588910247998; token=74df87625944f8a7e8ab647dfb07355357cecc5f82a39ce1419313dd391cce176d274309b40cf887590a; openid=7171ca619c737a3a4975097681d64e2d; sensorsdata2015jssdkcross=data%3Aenc%3B%0A%2Fqv%02%03v%7Bp%03lvq%2FG%2FD%3ED%3EpnC%3EFpD%40Dn%40nAFDB%3DFDCE%3EqCAr%3Fq%2F9%2Fsv%01%02%03lvq%2FG%2F%3EE%3F%40qFp%40%3EooAC%3F%3A%3DoB%3EnrC%40FD%40CAnE%3ABA%40DFD%3E%3A%40D%3DFAA%3A%3EE%3F%40qFp%40%3Eop%3EBr%3E%2F9%2F%7D%01%7C%7D%02%2FG%0A%2F1yn%03r%02%03l%03%01nssvpl%02%7C%04%01prl%03%08%7Dr%2FG%2F%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%2F9%2F1yn%03r%02%03l%02rn%01pulxr%08%06%7C%01q%2FG%2F%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BCl%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%2F9%2F1yn%03r%02%03l%01rsr%01%01r%01%2FG%2F%2F%0C9%2F1qr%05vprlvq%2FG%2F%3EE%3F%40qFp%40%3EooAC%3F%3A%3DoB%3EnrC%40FD%40CAnE%3ABA%40DFD%3E%3A%40D%3DFAA%3A%3EE%3F%40qFp%40%3Eop%3EBr%3E%2F%0C"}'
          data: '{}'
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
