name: dialy on build
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 21 * * *'
    # UTC时间，分别对应了北京时间的8点、13点、19点的整点和30分

jobs:
    deployment:
      runs-on: ubuntu-latest
      steps:
      - name: Deploy Stage
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://mktop.ppdai.com/api/mktop/checkInActivityJoinService/getHomePageInfo'
          method: 'POST'
          customHeaders: '{"cookie": "tagged=hotfix_20220928_modifyuploadurl_l_2022-10-10_6-A; regSourceId=0; referID=0; fromUrl=; referDate=2022-11-11%2013%3A28%3A46; currentUrl=https%3A%2F%2Faccount.ppdai.com%2Fh5%2Flogin%3Freturnurl%3Dhttps%253a%252f%252ftest.ppdai.com%253a3000%252fview%252f134218073%252f1%252f%253fcsr%253dtrue; token=29d988685944f8a7e8ab647dfb073553d1191504d427dedfe7d663be251448969c79f8ca89dab07adde4; openid=7171ca619c737a3a4975097681d64e2d; aliyungf_tc=a9c6b51d1dac29fce4ffcd11a4d25fb1c220f62b5835525ca620087b88c8cc2f; tagged=release_20221108_8_2022-11-07_4-A"}'
          data: '{}'
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
      - name: double11
        id: double11request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://acptpl.ppdai.com/api/invoper/doubleEleven/signUpMaoTai'
          method: 'POST'
          customHeaders: '{"cookie": "tagged=hotfix_20220928_modifyuploadurl_l_2022-10-10_6-A; regSourceId=0; referID=0; fromUrl=; referDate=2022-11-11%2013%3A28%3A46; currentUrl=https%3A%2F%2Faccount.ppdai.com%2Fh5%2Flogin%3Freturnurl%3Dhttps%253a%252f%252ftest.ppdai.com%253a3000%252fview%252f134218073%252f1%252f%253fcsr%253dtrue; token=29d988685944f8a7e8ab647dfb073553d1191504d427dedfe7d663be251448969c79f8ca89dab07adde4; openid=7171ca619c737a3a4975097681d64e2d; aliyungf_tc=a9c6b51d1dac29fce4ffcd11a4d25fb1c220f62b5835525ca620087b88c8cc2f; tagged=release_20221108_8_2022-11-07_4-A"}'
          data: '{"activityType":1060}'
      - name: Show double11 Response
        run: |
          echo ${{ steps.double11request.outputs.response }}
